export type IconName =
  | 'close'
  | 'check'
  | 'trash-bin'
  | 'user-add'
  | 'user-settings'
  | 'users'
  | 'user-circle'
  | 'arrow-right-to-bracket'
  | 'arrow-down-to-bracket'
  | 'arrow-up-from-bracket'
  | 'sort-horizontal'
  | 'wallet'
  | 'chart-line-up'
  | 'moon'
  | 'sun'
  | 'flag-es'
  | 'flag-en'
  | 'bars'
  | 'ellipsis-vertical'
  | 'edit'
  | 'plus'
  | 'circle-plus'
  | 'filter'
;