name: Build and Test Frontend

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "frontend/**"
      - ".github/workflows/angular.yml"
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - "frontend/**"
      - ".github/workflows/angular.yml"

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - run: echo "No changes in frontend/, skipping."