name: Build and Test API

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "api/**"
      - ".github/workflows/dotnet.yml"
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - "api/**"
      - ".github/workflows/dotnet.yml"

jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
      - run: echo "No changes in api/, skipping."