name: Build and Test API

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'api/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'api/**'

jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
      - run: echo "No changes in api/, skipping."